### PR TITLE
docs(saas): reorganize and rewrite content in preparation for saas

### PR DESCRIPTION
**Pull request by 317brian**

### CODE REVIEW

**Comment by aimeeu** [comment]
@brian-armory a little confused when I see _Armory Admin_ and _Administration_ -- maybe rename _Administration_ to _Spinnaker Administration_?

**Comment by 317brian** [comment]
> @brian-armory a little confused when I see _Armory Admin_ and _Administration_ -- maybe rename _Administration_ to _Spinnaker Administration_?

_Administration_ is going away. 

We'll have `Armory Admin` for on-prem admin tasks and `Armory Cloud Admin` for the SaaS equivalents. 

```
- Overview
- Installation
- Armory Admin
- Armory Cloud Admin
- User Guides
- Release Notes
- Plugins
```
In my head, these are the top lvl items. `Armory` (or `Armory Platform`) is the name for on-prem and `Armory Cloud` is the name for SaaS.

**Comment by aimeeu** [comment]
> We'll have `Armory Admin` for on-prem admin tasks and `Armory Cloud Admin` for the SaaS equivalents.

What do you think of  'Armory Server Admin' and 'Armory Cloud Admin' ?? Thinking of products like Jira that use 'Server' vs 'Cloud'

**Review by aimeeu — APPROVED** [review]
LGTM; tested about 10 redirects and they worked as expected

**Pull request merged**
