### PR TITLE
docs(agent): RBK-223 replace kubesvc w/ armory-agent

### PR DESCRIPTION
**Pull request by 317brian**
Resolves Jira: [RBK-223]

Outstanding questions:
- Will the Grafana dashboards be moved? Currently it's https://armory.jfrog.io/artifactory/manifests/kubesvc/armory-agent-dashboard.json
- Are the Agent plugin config options changing? They currently use `kubesvc`. I'm guessing no but would like to confirm.

[RBK-223]: https://armory.atlassian.net/browse/RBK-223

### CODE REVIEW

**Comment by german-muzquiz** [comment]
We'll need to change the grafana dashboards referencing kubesvc, but the config options will not change for now.

**Comment by 317brian** [comment]
@german-muzquiz I think this PR is good to go pending the following:

- The Docker Hub location moving to `armory/agent-kube-spinplug`
- The Grafana Dashboards moving

I can revert the hub location to the old `armory/kubesvc-plugin` location and have follow up PRs for that and the Grafana change if we want to get this one out the door.

**Comment by german-muzquiz** [comment]
@brian-armory rebranding was just released in `0.6.0` with these final changes:

* Docker images for agent service are published to armory/agent-k8s 
* Docker images for agent clouddriver plugin are published to armory/agent-k8s-spinplug
* Agent config file is renamed from kubesvc.yml to armory-agent.yml, and its location moved from `/opt/spinnaker/config` to `/opt/armory/config`
* Github repo armory-io/kubesvc is moved to armory-io/agent-k8s
* Github repo armory-io/kubesvc-plugin is moved to armory-io/agent-k8s-spinplug
* Released installation manifests for the agent service use armory-agent instead of kubesvc or spin. For example in deployment name, configmaps, metadata labels, namespace, etc. These manifests live in https://armory.jfrog.io/artifactory/manifests/agent-k8s
* Names in grafana dashboards were also changed to armory agent, but names of the actual metrics remain the same (prefixed by `kubesvc`)

**Comment by 317brian** [comment]
Thanks @german-muzquiz! I'll get these changes added.

**Pull request merged**
