### PR TITLE
chore(gh-integration): Updating Github integration plugin docs

### PR DESCRIPTION
**Pull request by christosarvanitis**
Resolves Jira: [CDSH-629]

deploy preview: https://deploy-preview-2236--armory-docs.netlify.app/plugins/github-integration/

1 Dec 2023
- Refactor "use.md" to folder with included images (moved images out of static directory); images should be in same dir as file for better image compression and loading times
- Create "overview" page and move github-integration-plugin/_index.md content to overview; this is the pattern we use in CDaaS docs.
- Add new features to overview; add links to features list

[CDSH-629]: https://armory.atlassian.net/browse/CDSH-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by link108 — APPROVED** [review]

**Comment by aimeeu** [comment]
do not merge until I'm done with style guide updates

**Comment by aimeeu** [comment]
Changed to Draft status since there are 2 sections in the advanced configuration file that don't have content yet

Moved the new confiigure features file to the "Get Started" section to match how I structured our other plugin content (like Terraform Integration)

**Comment by aimeeu** [comment]
Kyle's comments https://cloud-armory.slack.com/archives/CH4RVCCTS/p1700677176880459

But will also note them here
I would like a separate page for each feature
So 1 for Authorization (AuthZ)
1 for Validate GitHub Access
1 for Configure GitHub Commit Status Echo notifications

The Overview page should be updated to include references to these new features as additional use cases so there is a single list of all the "sub features" of the GitHub Integration Plugin in one place

The three features above need more information added to either the Overview Page or the indvidual configuration pages explaining why the feature is useful and what benefit it will bring (or drawback of leaving it off)

**Comment by christosarvanitis** [comment]
@aimeeu Do you think that this PR is ready to be merged? Or is anything else needed in terms of styling, content etc?

**Review by aimeeu — APPROVED** [review]

**Comment by kyledmitchell** [comment]
This looks good from my perspective.  Thanks for making all those changes @aimeeu.

**Pull request merged**
