### PR TITLE
chore(halyard): add deprecation notice for halyard

### PR DESCRIPTION
**Pull request by dogonthehorizon**
**Internal RFC period is open today until EOD 2021/06/24**

### CODE REVIEW

**Review by alexmbe — COMMENTED** [review]
To make this consistent with PaCRD wording. Also @brian-armory we should add the Last Support Release column to the /deprecations page table.

On 2021/09/01, Halyard will be deprecated with an End of Support date of 2021/12/30. This means that after 2021/09/01, no new development is done specific to the feature except for critical (P0/1) bugs and security CVE fixes. Support for critical (P0/1) bugs and security CVE fixes will end on 2021/12/30. You will still be able to access and use the tool to install and configure Armory Enterprise releases up to and including 2.26. This means that any workflow that uses Halyard may break when you upgrade to a release that comes out after 2.26

**Comment by alexmbe** [comment]
The Help Center link is not pointing to https://support.armory.io/support, and the wording is different from what we have in pacrd deprecation notice. Should just copy that.

**Comment by dogonthehorizon** [comment]
LGTM based on @brian-armory 's changes!

**Review by 317brian — APPROVED** [review]
lgtm

**Pull request merged**
