### PR TITLE
docs(2.28.0): Update armoryspinnaker_v2-28-0.md

### PR DESCRIPTION
**Pull request by mknous**
This is a draft for JPMC when we hand off the RCs to them - please DON"T MERGE this yet. Cameron has to add the "hidden" flag.  We have to go back and add the breaking changes.

Resolves GitHub issue: <link to GH issue>

Resolves Jira: [JIRAPROJECT-123]

### CODE REVIEW

**Comment by link108** [comment]
updated 👍

**Comment by mknous** [comment]
The following items need to be addressed in the final version:

- [x] Breaking change called out by Jason - https://armory.atlassian.net/browse/DYN-289?focusedCommentId=84270
- [x] Remove disclaimer
- [x] Confirm plugin versions are correct (Policy Engine is per Marcia)
- [x] Anything new since R8 that has to be added
- [x] Remove Known Issue Clicking the “Create Server Group” button does not work for an AWS provider.
- [x] Check whether Known Issues Bake Failure needs to be removed
- [x] Check to see if any other features should be added
- [x] Agent plugin version needs to be 0.11.0 
- [x] Remove Launch Templates section as we will not be using it this time
- [x] Include a short blurb about bumping the JVM versions.
- [ ] Update Lambda Plugin if new version works
- [ ] Update External Accounts to 0.3.0

**Comment by mknous** [comment]
Per RUBIK team, the Agent version will need to be updated to 0.11.0 instead of what is currently listed.

**Review by link108 — COMMENTED** [review]
chore(build): updating to 2.28.0 images

**Review by link108 — COMMENTED** [review]
chore(plugins): Updating plugin versions

**Review by link108 — APPROVED** [review]

**Pull request merged**
