### PR TITLE
feat(releaseNotes): implement spinnaker release notes action

### PR DESCRIPTION
**Pull request by edgarulg**
This PR implements a GHA to create the release notes for Armory spinnaker.

This action will be triggered by Astrolabe as part of the Automation release process.

Under de hood, the action uses [this](https://docs.gomplate.ca/) tool to render the payload into the release notes template.

### CODE REVIEW

**Review by 317brian — COMMENTED** [review]
Does this need to wait for the discussions in the astrolabe repo to be resolved? If not, this will be a great change since it'll make it easier for the doc team to update the template in the future.

**Comment by edgarulg** [comment]
@brian-armory this change does not need to wait for something in Astrolabe. The reason I moved this template and implements the action is to do the exact thing you mentioned.

I want to enable the docs team to independently modify your templates without depending on the release process. So every time we created a new final release the automation will trigger the Action to generated the release notes using the template in the master branch.

In the other hand, if the docs team want to have more data to be included in the release notes you can talk with us and we will include this extra data in the payload to be use in the template.

This will put a precedent to start moving templates to this repository and we will send the data needed for them to automate more things :D

**Review by 317brian — APPROVED** [review]
I'm good with this on the docs side. Did you want any of the reviewers from the Eng side to take a look before we merge?

**Comment by edgarulg** [comment]
@brian-armory I'm not expecting to have an approval for ENG, so feel free to merge it when you are ready

**Pull request merged**
