### PR TITLE
feat(pcm): add deployment targets from clouddriver

### PR DESCRIPTION
**Pull request by kevinawoo**

### CODE REVIEW

**Comment by aimeeu** [comment]
Well in my attempt to rebase to get the correct .github/workflows/mlc_config.json, I seemed to have totally foobarred this PR.

**Comment by aimeeu** [comment]
Replaced by PR 222

**Review by aimeeu — APPROVED** [review]

**Comment by kevinawoo** [comment]
reopened, this is the correct one

**Comment by kevinawoo** [comment]
closing in favor of a combined one for CAPI https://github.com/armory/docs/pull/219

**Pull request closed without merging**
