### PR TITLE
docs(plugin): Added page for SelfServeErrorManagement plugin.

### PR DESCRIPTION
**Pull request by DanielaS12**
Resolves issue: [CDSH-761]

deploy preview https://deploy-preview-2241--armory-docs.netlify.app/plugins/self-serve-error-management/

[CDSH-761]: https://armory.atlassian.net/browse/CDSH-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by aimeeu — APPROVED** [review]

**Review by kyledmitchell — APPROVED** [review]

**Review by kyledmitchell — CHANGES_REQUESTED** [review]
We need to add the beta label at top of screen next to "proprietary"

image

**Comment by kyledmitchell** [comment]
@aimeeu Does the Compatibility Matrix table here follow a pattern on other pages where we are listing the min version and it is assumed future supported versions also supported or should we be explicit and have another row for 1.30.x

image

**Comment by aimeeu** [comment]
@kyledmitchell updated to include Beta image and Spinnaker versions 1.29-1.31 in compat matrix

**Comment by kyledmitchell** [comment]
This looks good to me and is ready to be published.

**Pull request merged**
